import { TabKey } from "./Types";

export const tabContent: Record<TabKey, any[]> = {
  "Merry Set": [
    {
      type: "Merry Set",
      bgCardColor: "bg-[#FFF3E6]",
      bgColor: "bg-[#FFC88D]",
      borderColor: "border-[#B56106]",
      textColor: "text-[#B56106]",
      package: "Bronze Package",
      benefits: [
        "Branded Keyholder (10 Pieces)",
        "Stylus Pen (10 Pieces)",
        "Umbrella (10 Pieces)",
        "Branded Reusable Bottle (10  Pieces)",
        "Season Greeting Card (5 Pieces)",
      ],
      price: "One Hundred Thousand Naira Only (100,000)",
    },
    {
      type: "Merry Set",
      bgCardColor: "bg-[#D8DCFF]",
      bgColor: "bg-[#DBC3FF]",
      borderColor: "border-[#5F29B3]",
      textColor: "text-[#5F29B3]",
      package: "Silver Package",
      benefits: [
        "Branded Umbrella (10 Pieces)",
        "Branded Table Notepad (10 Pieces)",
        "Branded Towel (5 Pieces)",
        "Branded Keyholder (10 Pieces)",
        "Branded Reusable Bottle (10 Pieces)",
      ],
      price: "Two Hundred Thousand Naira Only (200,000)",
    },
    {
      type: "Merry Set",
      bgCardColor: "bg-[#E7F1FD]",
      bgColor: "bg-[#8FC0F7]",
      borderColor: "border-[#064083]",
      textColor: "text-[#064083]",
      package: "Gold Package",
      benefits: [
        "Branded Notepad (10 Pieces)",
        "Branded Umbrella (10 Pieces)",
        "Branded Towel (5 Pieces)",
        "Branded Stylus Pen (10 Pieces)",
        "Branded Table Calendar (10 Pieces)",
        "Branded Wall Calendar (10 Pieces)",
        "Branded Keyholder (10 Pieces)",
      ],
      price: "Three Hundred & Fifty Thousand Naira Only (350,000)",
    },
    {
      type: "Merry Set",
      bgCardColor: "bg-[#F3FFCF]",
      bgColor: "bg-[#F3FFEA]",
      borderColor: "border-[#496E2D]",
      textColor: "text-[#496E2D]",
      package: "Platinum Package",
      benefits: [
        "Branded Table Notepad (10 Pieces)",
        "Branded Umbrella (10 Pieces)",
        "Branded Keyholder (10 Pieces)",
        "Branded Table Calendar (10 Pieces)",
        "Branded Tote Bag (10 Pieces)",
        "Branded Stylus Pen (10 Pieces)",
        "Branded Reusable Bottle (20 Pieces)",
        "Branded Wall Calendar (10 Pieces)",
      ],
      price: "Five Hundred Thousand Naira Only (500,000)",
    },
  ], // Content for the first tab
  "Yelutide Treasure Trove": [
    {
      type: "Yelutide Treasure Trove",
      bgCardColor: "bg-[#FFF3E6]",
      bgColor: "bg-[#FFC88D]",
      borderColor: "border-[#B56106]",
      textColor: "text-[#B56106]",
      package: "Bronze Package",
      benefits: [
        " Branded Table Calendar (10 pieces)",
        "Branded Table Notepad (10 pieces)",
        "Branded Keyholder (10 pieces)",
        "Branded Desk Lamp (6 pieces)",
        "Season Greeting Card (10 pieces)",
      ],
      price: "Two Hundred Thousand Naira Only (200,000)",
    },
    {
      type: "Yelutide Treasure Trove",
      bgCardColor: "bg-[#D8DCFF]",
      bgColor: "bg-[#DBC3FF]",
      borderColor: "border-[#5F29B3]",
      textColor: "text-[#5F29B3]",
      package: "Silver Package",
      benefits: [
        "Wall Calendar (10 Pieces)",
        "Table Notepad (10 pieces)",
        "Reusable Water Bottle (10 Pieces)",
        "Umbrella (20  Pieces)",
        "Stylus Pen (20 Pieces)",
        "Keyholder (20 Pieces)",
        "Tote Bag (10 pieces)"
      ],
      price: "Three Hundred and Fifty Thousand Naira Only (350,000)",
    },
    {
      type: "Yelutide Treasure Trove",
      bgCardColor: "bg-[#E7F1FD]",
      bgColor: "bg-[#8FC0F7]",
      borderColor: "border-[#064083]",
      textColor: "text-[#064083]",
      package: "Gold Package",
      benefits: [
        "Branded Table Calendar  (10 Pieces)",
        "Branded Table Clock (10 Pieces)",
        "Branded Table Notepad (10 Pieces)",
        "Brand Reusable Bottle (10 Pieces)",
        "Branded Desk Lamp (5 Pieces)",
        "Branded Tote Bag (5 Pieces)",
        "Branded Keyholder (10 Pieces)",
        "Branded Stylus Pen (10 Pieces)",
        "Branded Laptop Bag (5 Pieces)",
        "Season Greeting Card (10 Pieces)",
      ],
      price: "Five Hundred Thousand Naira Only (500,000)",
    },
    {
      type: "Yelutide Treasure Trove",
      bgCardColor: "bg-[#F3FFCF]",
      bgColor: "bg-[#F3FFEA]",
      borderColor: "border-[#496E2D]",
      textColor: "text-[#496E2D]",
      package: "Platinum Package",
      benefits: [
        "Branded Laptop Bag (10 Pieces)",
        "Branded Table Calendar (10 Pieces)",
        "Branded Wall Calendar (10 Pieces)",
        "Branded Reusable Bottle (10 Pieces)",
        "Branded Table Clock (10 Pieces)",
        "Branded Table Notepad (10 Pieces)",
        "Branded Desk Lamp (10 Pieces)",
        "Branded Keyholder (10 Pieces)",
        "Branded Stylus Pen (10 Pieces)",
        "Branded Umbrella (10 Pieces) "
      ],
      price: "Seven Hundred Thousand Naira Only (700,000)",
    },
  ], // Content for the second tab
  // Add more tabs as needed
};
